version: "3.7"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysqldb
    networks:
      - spring-network
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    working_dir: /spring-app
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    image: $REGISTRY
    restart: on-failure
    container_name: $SPRING_CONTAINER
    networks:
      - spring-network
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExists=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/var/lib/tpachat
    stdin_open: true
    tty: true
networks:
  spring-network:
    name: spring-network
volumes:
  db:
  .m2: