version: "3.7"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_DOCKER_PORT:$MYSQLDB_LOCAL_PORT
    volumes:
      - db:/var/lib/mysql


  tpachat:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    image: tpachat-image
    container_name: tpachat-container
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_DOCKER_PORT:$SPRING_LOCAL_PORT
    networks:
      - bored-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_LOCAL_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/var/lib/tpachat
    stdin_open: true
    tty: true
networks:
  bored-network:
    name: bored-network
volumes:
  db:
  .m2:
