version: "3.7"

services:
  
  app:
    working_dir: /spring-app
    build:
      context: .
      dockerfile: Dockerfile
    image: $REGISTRY
    restart: on-failure
    container_name: $SPRING_CONTAINER
    networks:
      - spring-network
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/tpachat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExists=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/var/lib/tpachat
    stdin_open: true
    tty: true
networks:
  spring-network:
    name: spring-network
volumes:
  .m2:
