version: "3.7"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysqldb
    networks:
      - spring-network
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
#  app:
#    working_dir: /spring-app
#    depends_on:
#      - mysqldb
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: $REGISTRY:$TAG
#    restart: on-failure
#    container_name: $SPRING_CONTAINER
#    networks:
#      - spring-network
#    env_file: ./.env
#    ports:
#      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExists=true",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2:/root/maven-repo
#    stdin_open: true
    tty: true
#    command: mvn test



#  sonarqube:
#    image: sonarqube:8.9.7-community
#    ports:
#      - "9000:9000"
#      - "9092:9092"
#    volumes:
#      - 'SonarQube_data:/opt/SonarQube/data'
#      - 'SonarQube_extensions:/opt/SonarQube/extensions'
#      - 'SonarQube_logs:/opt/SonarQube/logs'
#    networks:
#      - spring-network
#    stdin_open: true
#    tty: true
#
#
#  nexus:
#    image: sonatype/nexus3
#    ports:
#      - "8081:8081"
#    volumes:
#      - 'nexus-data:/nexus-data'
#    networks:
#      - spring-network

networks:
  spring-network:
    name: spring-network

volumes:
  db:
  .m2:

